headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/vaidikpatel/Downloads/Home/Num Nums Bakery/Website"
publishOrigin = "default"
base = "/Users/vaidikpatel/Downloads/Home/Num Nums Bakery/Website"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"