/**
 * The one email design. Every email this business sends is built from here.
 *
 * There are three — the coupon code (Resend, from `subscribe.mjs`), and
 * Supabase's **Confirm signup** and **Reset password**, which are static HTML
 * pasted into the Supabase dashboard and generated by
 * `scripts/build-auth-emails.mjs`. Keeping the shell in one module is the only
 * reason they cannot drift into three different-looking bakeries.
 *
 * Built to `brand_assets/num_nums_brand_guidelines.html`: Rose Petal #C85478,
 * Vanilla Cream #FFF8F2, Soft Dough #F5EBE0, Dark Espresso #2C1A0E, Warm
 * Chestnut #5C3A22. **Jost for headings AND body** (see DISPLAY below —
 * this deliberately overrides the guide's Cormorant-for-display line), Jost
 * never above weight 500. **No Riverstone Teal (#4EC4D8)** — it is
 * location-specific and every one of these is a global send.
 *
 * Email is not the web:
 * - **Tables, not flex/grid.** Outlook renders through Word and ignores both.
 * - **Inline styles.** The <style> block carries only media queries and dark
 *   mode; throw the whole block away and the mail is still correct.
 * - **Anything that must be read is live text, never an image.** Most inboxes
 *   block images by default, so a code or a link baked into a picture is a
 *   dead end. `Logo_TParent` is the only image, it has real alpha so it needs
 *   no plate behind it, and the wordmark under it is text — a blocked image
 *   still leaves a masthead.
 * - **Always send a plain-text part too.** HTML-only mail scores worse with
 *   spam filters and is unreadable in a text client.
 */

export const PROD = 'https://numnumsbakery.com.au';

/**
 * Headings are **Jost**, not Cormorant.
 *
 * Vaidik's call, 2026-09-20: the serif reads decorative rather than modern at
 * heading sizes. This overrides the "Cormorant for display" line in
 * `brand_assets/num_nums_brand_guidelines.html` — the guide is older than the
 * decision. Cormorant is kept as ORNAMENT for the occasional one-line flourish
 * (the footer's "100% eggless. Made fresh daily."), never for a heading.
 *
 * Jost is set at 300 here because the guide's "never above 500" rule is about
 * weight, and a 38px heading at 300 is what makes a geometric sans read as
 * considered rather than shouty.
 */
export const DISPLAY = "'Jost', 'Helvetica Neue', Helvetica, Arial, sans-serif";
export const ORNAMENT = "'Cormorant Garamond', Georgia, 'Times New Roman', serif";
export const BODY = "'Jost', 'Helvetica Neue', Helvetica, Arial, sans-serif";

export const esc = (s) => String(s).replace(/[<>&"']/g, (c) =>
  ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;' }[c]));

/**
 * Which host a link should point at.
 *
 * Hardcoding production meant every email sent from a deploy preview carried
 * a broken logo and dead links, so the one thing you could not check before
 * publishing was whether the email worked.
 *
 * **Allowlisted, because the host is attacker-controlled.** Echoing an
 * arbitrary Host into a link inside an email we send is how you get a phishing
 * page with our name on it; anything unrecognised falls back to production.
 */
export function siteFor(req) {
  let host;
  try { host = new URL(req.url).host; } catch { return PROD; }
  if (host === 'numnumsbakery.com.au' || host === 'www.numnumsbakery.com.au') return PROD;
  if (/^[a-z0-9-]+--numnumstest\.netlify\.app$/.test(host)) return `https://${host}`;
  if (host === 'numnumstest.netlify.app') return `https://${host}`;
  if (/^localhost(:\d+)?$/.test(host)) return `http://${host}`;
  return PROD;
}

/** A small-caps label with a rule running out either side of it. The site's
 *  own `.section-label` device, and the thing that frames a code. */
export const eyebrowRule = (label) => `
        <tr><td class="pad" style="padding:34px 56px 0 56px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td width="30%" class="rule" style="border-bottom:1px solid #EBD3DA;font-size:0;line-height:0;">&nbsp;</td>
              <td align="center" style="padding:0 12px;font-family:${BODY};font-size:10px;line-height:12px;letter-spacing:2.4px;text-transform:uppercase;color:#C85478;font-weight:500;white-space:nowrap;">${esc(label)}</td>
              <td width="30%" class="rule" style="border-bottom:1px solid #EBD3DA;font-size:0;line-height:0;">&nbsp;</td>
            </tr>
          </table>
        </td></tr>`;

/** A bulletproof button: a table cell with a background, so Outlook draws the
 *  whole shape instead of a bare link. */
export const button = (href, label) => `
        <tr><td class="pad" style="padding:30px 56px 0 56px;">
          <table role="presentation" cellpadding="0" cellspacing="0" border="0">
            <tr><td align="center" bgcolor="#C85478" style="background:#C85478;border-radius:3px;">
              <a href="${href}" style="display:inline-block;padding:15px 34px;font-family:${BODY};font-size:14px;line-height:18px;font-weight:500;letter-spacing:1.4px;text-transform:uppercase;color:#FFF8F2;text-decoration:none;">${esc(label)}</a>
            </td></tr>
          </table>
        </td></tr>`;

/** Body copy inside the card. */
export const para = (html, top = 16) => `
        <tr><td class="pad" style="padding:${top}px 56px 0 56px;">
          <p class="muted" style="margin:0;font-family:${BODY};font-size:15px;line-height:24px;color:#5C3A22;font-weight:300;">${html}</p>
        </td></tr>`;

/** Small print inside the card. */
export const fine = (html, top = 16) => `
        <tr><td class="pad" style="padding:${top}px 56px 0 56px;">
          <p class="muted" style="margin:0;font-family:${BODY};font-size:13px;line-height:20px;color:#8A6B55;font-weight:300;">${html}</p>
        </td></tr>`;

/**
 * Wrap body rows in the full document: masthead, card, footer.
 *
 * `unsubscribe` is passed ONLY for marketing mail. A password reset is
 * transactional — there is nothing to unsubscribe from, and offering it there
 * teaches people the link is meaningless.
 */
export function shell({ title, preheader, site = PROD, rows, unsubscribe = null }) {
  return `<!doctype html>
<html lang="en" dir="ltr" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light dark">
<meta name="supported-color-schemes" content="light dark">
<title>${esc(title)}</title>
<!--[if mso]>
<xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
<![endif]-->
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,400&family=Jost:wght@300;400;500&display=swap" rel="stylesheet">
<style>
  /* Progressive only. Everything here degrades to the inline styles. */
  body { margin:0; padding:0; width:100% !important; }
  img { border:0; line-height:100%; outline:none; text-decoration:none; -ms-interpolation-mode:bicubic; }
  table { border-collapse:collapse !important; }
  a { color:#C85478; }
  .lift { box-shadow: 0 1px 2px rgba(44,26,14,.04), 0 8px 24px -12px rgba(44,26,14,.16); }
  @media screen and (max-width:620px) {
    .wrap { width:100% !important; }
    .pad { padding-left:24px !important; padding-right:24px !important; }
    .h1 { font-size:30px !important; line-height:36px !important; }
    .code { font-size:26px !important; letter-spacing:4px !important; }
  }
  /* Apple Mail and iOS honour this. Gmail force-inverts on its own and ignores
     it, which is why no colour below does structural work — the mail is
     legible with this whole block dropped. */
  @media (prefers-color-scheme: dark) {
    .canvas { background:#17100A !important; }
    .card   { background:#241709 !important; }
    .panel  { background:#31200F !important; }
    .ink    { color:#FFF8F2 !important; }
    .muted  { color:#D9C6B6 !important; }
    .foot-display { color:#FFF8F2 !important; }
    .foot         { color:#C9B4A3 !important; }
    .foot a       { color:#C9B4A3 !important; }
    .rule         { border-color:#4A3423 !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background:#FFF8F2;">

<div style="display:none;font-size:1px;color:#FFF8F2;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">${esc(preheader)}&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;</div>

<table role="presentation" class="canvas" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#FFF8F2;">
<tr><td align="center" style="padding:32px 12px 48px 12px;">

  <table role="presentation" class="wrap" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;">

    <tr><td class="card lift" style="background:#FFFFFF;border-radius:4px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">

        <!-- A 3px rose cap instead of a border all the way round: the guide's
             pink-first rule stated once, rather than a box shouting it. -->
        <tr><td style="background:#C85478;height:3px;line-height:3px;font-size:3px;border-radius:4px 4px 0 0;">&nbsp;</td></tr>

        <!-- Logo_TParent: real alpha, so it needs no white plate and no badge,
             which is what makes it the one to reach for. It carries no
             wordmark, so the name below it is live text — a blocked image
             still leaves a masthead rather than a lone alt string. -->
        <tr><td align="center" style="padding:34px 24px 2px 24px;">
          <a href="${site}" style="text-decoration:none;">
            <img src="${site}/brand_assets/email-logo.png" width="104" alt=""
                 style="display:block;width:104px;max-width:104px;height:auto;border:0;">
          </a>
        </td></tr>
        <tr><td align="center" style="padding:10px 24px 0 24px;">
          <div class="ink" style="font-family:${ORNAMENT};font-size:23px;line-height:28px;font-weight:600;letter-spacing:.01em;color:#2C1A0E;">Num Num&#39;s Bakery</div>
          <div style="margin-top:5px;font-family:${BODY};font-size:9px;line-height:11px;font-weight:500;letter-spacing:2.6px;text-transform:uppercase;color:#C85478;">100% Eggless</div>
        </td></tr>
${rows}
        <tr><td style="height:46px;line-height:46px;font-size:46px;">&nbsp;</td></tr>
      </table>
    </td></tr>

    <!-- Sender identity is a Spam Act 2003 obligation on a commercial message,
         not decoration. The unsubscribe is too, and only on marketing mail. -->
    <tr><td style="padding:36px 8px 0 8px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr><td align="center" class="pad foot" style="padding:0 24px;">
          <p class="foot-display" style="margin:0 0 4px 0;font-family:${ORNAMENT};font-size:19px;line-height:26px;color:#2C1A0E;font-style:italic;">100% eggless. Made fresh daily.</p>
          <p class="foot" style="margin:0 0 16px 0;font-family:${BODY};font-size:13px;line-height:21px;color:#5C3A22;font-weight:300;">
            Harris Park &middot; Shop 1, 96&ndash;98 Wigram Street<br>
            Riverstone &middot; Shop 8, Riverstone Shopping Centre
          </p>
          <p class="foot" style="margin:0;font-family:${BODY};font-size:12px;line-height:19px;color:#8A6B55;font-weight:300;">
            GNT Ventures Pty Ltd &middot; ABN 39 634 402 412
          </p>
          ${unsubscribe ? `<p class="foot" style="margin:14px 0 0;font-family:${BODY};font-size:12px;line-height:19px;color:#8A6B55;font-weight:300;">
            You&#39;re getting this because you asked for a discount code at numnumsbakery.com.au.<br>
            <a href="${unsubscribe}" style="color:#8A6B55;text-decoration:underline;">Unsubscribe</a>
          </p>` : ''}
        </td></tr>
      </table>
    </td></tr>

  </table>

</td></tr>
</table>
</body>
</html>`;
}

/** The footer, as plain text. Every message ends the same way. */
export const textFooter = (unsubscribeUrl = null) => [
  '--',
  "Num Num's Bakery - 100% eggless, made fresh daily",
  'Harris Park, Shop 1, 96-98 Wigram Street',
  'Riverstone, Shop 8, Riverstone Shopping Centre',
  'GNT Ventures Pty Ltd, ABN 39 634 402 412',
  ...(unsubscribeUrl ? ['', `Unsubscribe: ${unsubscribeUrl}`] : []),
].join('\n');
